namespace F1_Data_Management
{
    public enum Track
    {
        Albert_Park_Circuit,
        Circuit_Paul_Ricard,
        Shanghai_International_Circuit,
        Bahrain_International_Circuit,
        Cicuit_de_Barcelona_Catalunya,
        Circuit_de_Monaco,
        Circuit_Gilles_Villeneuve,
        Silverstone_Circuit,
        Hockenheimring,
        Hungaroring,
        Circuit_de_Spa_Francorchamps,
        Autodromo_Nazionale_Monza,
        Marina_Bay_Street_Circuit,
        Suzuka_Circuit,
        Yas_Marina_Circuit,
        Circuit_of_the_Americas,
        Autodromo_Jose_Carlos_Pace,
        Red_Bull_Ring,
        Sochi_Autodrom,
        Autodromo_Hermanos_Rodriguez,
        Baku_City_Circuit,
        Bahrain_International_Circuit_Short,
        Silverstone_Circuit_Short,
        Circuit_of_the_Americas_Short,
        Suzuka_Circuit_Short,
        Hanoi_Street_Circuit,
        Circuit_Zandvoort
    }
}